Resources:
  PrivateSubnetOne:
    Type: AWS::EC2::Subnet
    Condition: CreateNetworkResources
    Properties:
      VpcId: ${self:resources.Outputs.VpcId.Value}
      CidrBlock:
        Fn::Select:
          - 0
          - Fn::Cidr:
              - ${self:custom.vpc.cidr}
              - 12
              - 8
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: ${self:service}-${self:provider.stage}-private-subnet-1

  PrivateSubnetOneRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateNetworkResources
    Properties:
      SubnetId: ${self:resources.Outputs.PrivateSubnetOne.Value}
      RouteTableId: ${self:resources.Outputs.PrivateRouteTableOne.Value}

  PrivateSubnetTwo:
    Type: AWS::EC2::Subnet
    Condition: CreateNetworkResources
    Properties:
      VpcId: ${self:resources.Outputs.VpcId.Value}
      CidrBlock:
        Fn::Select:
          - 1
          - Fn::Cidr:
              - ${self:custom.vpc.cidr}
              - 12
              - 8
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: ${self:service}-${self:provider.stage}-private-subnet-2

  PrivateSubnetTwoRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateNetworkResources
    Properties:
      SubnetId: ${self:resources.Outputs.PrivateSubnetTwo.Value}
      RouteTableId: ${self:resources.Outputs.PrivateRouteTableTwo.Value}

  PublicSubnetOne:
    Type: AWS::EC2::Subnet
    Condition: CreateVpc
    Properties:
      VpcId: ${self:resources.Outputs.VpcId.Value}
      CidrBlock:
        Fn::Select:
          - 2
          - Fn::Cidr:
              - ${self:custom.vpc.cidr}
              - 12
              - 8
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: ${self:service}-${self:provider.stage}-public-subnet-1

  PublicSubnetOneRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateVpc
    Properties:
      SubnetId: ${self:resources.Outputs.PublicSubnetOne.Value}
      RouteTableId: ${self:resources.Outputs.PublicRouteTable.Value}

  PublicSubnetTwo:
    Type: AWS::EC2::Subnet
    Condition: CreateVpc
    Properties:
      VpcId: ${self:resources.Outputs.VpcId.Value}
      CidrBlock:
        Fn::Select:
          - 3
          - Fn::Cidr:
              - ${self:custom.vpc.cidr}
              - 12
              - 8
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: ${self:service}-${self:provider.stage}-public-subnet-2

  PublicSubnetTwoRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateVpc
    Properties:
      SubnetId: ${self:resources.Outputs.PublicSubnetTwo.Value}
      RouteTableId: ${self:resources.Outputs.PublicRouteTable.Value}
