service: ${env:SERVICE_NAME, 'DocumentDB'}

useDotenv: true

custom:
  documentdb:
    clusterIdentifier: ${self:service}-${sls:stage}-${param:DocumentDBClusterIdentifier, env:DOCUMENTDB_CLUSTER_IDENTIFIER}
    masterUsername: ${param:DocumentDBMasterUsername, env:DOCUMENTDB_MASTER_USERNAME}
    database: ${param:DocumentDBDatabaseName, env:DOCUMENTDB_DATABASE_NAME}
  vpc:
    cidr: ${param:VpcCidr, env:VPC_CIDR, '10.0.0.0/16'}

provider:
  name: aws
  deploymentBucket:
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

# variables are used to reference resources created in this stack and other stacks
# based on the service name, stage, conditions, and region.
# Check out the content of the file to see how it works.
variables: ${file(./variables.yml)}

resources:
  - ${file(./resource/Conditions.yml)}
  - ${file(./resource/VPC.yml)}
  - ${file(./resource/VPCGateways.yml)}
  - ${file(./resource/VPCEndpoints.yml)}
  - ${file(./resource/VPCSubnets.yml)}
  - ${file(./resource/VPCRoutes.yml)}
  - ${file(./resource/DocumentDB.yml)}
  - ${file(./resource/DocumentDBSecrets.yml)}
  - ${file(./resource/Cloud9env.yml)}
  - ${file(./resource/Outputs.yml)}
