service: ${env:SERVICE_NAME, 'RDS'}

useDotenv: true

custom:
  RDS:
    clusterIdentifier: ${self:service}-${self:provider.stage}-${env:RDS_CLUSTER_IDENTIFIER}
    masterUsername: ${env:RDS_MASTER_USERNAME}
    database: ${env:RDS_DATABASE_NAME}
  vpc:
    cidr: ${env:VPC_CIDR, '10.0.0.0/16'}

provider:
  name: aws
  stage: ${opt:stage, env:STAGE, 'local'}
  region: ${opt:region, env:AWS_REGION, 'us-east-1'}
  profile: ${opt:aws-profile, env:AWS_PROFILE, ''}

resources:
  Conditions:
    CreateRDSCluster:
      Fn::Equals:
        - ${param:skipRDSClusterCreation, env:SKIP_RDS_CLUSTER_CREATION, 'false'}
        - "false"
    CreateNetworkResources:
      Fn::Equals:
        - ${param:skipNetworkResources, env:SKIP_NETWORK_RESOURCES, 'false'}
        - "false"
    CreateVpc:
      Fn::And:
        - Condition: CreateNetworkResources
        - Fn::Equals:
            - ${param:vpcId, env:VPC_ID, ''}
            - ""

  Resources:
    RDSConnectionSecret: ${file(./resources/RDSConnectionSecret.yml)}
    RDSPostgreSqlInstance: ${file(./resources/RDSPostgreSqlInstance.yml)}
    RDSSecurityGroup: ${file(./resources/RDSSecurityGroup.yml)}
    RDSSubnetGroup: ${file(./resources/RDSSubnetGroup.yml)}
    VPC: ${file(./resources/VPC.yml)}
    InternetGateway: ${file(./resources/InternetGateway.yml)}
    GatewayAttachment: ${file(./resources/GatewayAttachment.yml)}
    NatGatewayOne: ${file(./resources/NatGatewayOne.yml)}
    NatGatewayOneAttachment: ${file(./resources/NatGatewayOneAttachment.yml)}
    NatGatewayTwo: ${file(./resources/NatGatewayTwo.yml)}
    NatGatewayTwoAttachment: ${file(./resources/NatGatewayTwoAttachment.yml)}
    PublicSubnetOne: ${file(./resources/PublicSubnetOne.yml)}
    PublicSubnetTwo: ${file(./resources/PublicSubnetTwo.yml)}
    PublicRoute: ${file(./resources/PublicRoute.yml)}
    PublicRouteTable: ${file(./resources/PublicRouteTable.yml)}
    PublicSubnetOneRouteTableAssociation: ${file(./resources/PublicSubnetOneRouteTableAssociation.yml)}
    PublicSubnetTwoRouteTableAssociation: ${file(./resources/PublicSubnetTwoRouteTableAssociation.yml)}
    PrivateSubnetOne: ${file(./resources/PrivateSubnetOne.yml)}
    PrivateSubnetTwo: ${file(./resources/PrivateSubnetTwo.yml)}
    PrivateRouteOne: ${file(./resources/PrivateRouteOne.yml)}
    PrivateRouteTwo: ${file(./resources/PrivateRouteTwo.yml)}
    PrivateRouteTableOne: ${file(./resources/PrivateRouteTableOne.yml)}
    PrivateRouteTableTwo: ${file(./resources/PrivateRouteTableTwo.yml)}
    PrivateSubnetOneRouteTableAssociation: ${file(./resources/PrivateSubnetOneRouteTableAssociation.yml)}
    PrivateSubnetTwoRouteTableAssociation: ${file(./resources/PrivateSubnetTwoRouteTableAssociation.yml)}
    Cloud9env: ${file(./resources/Cloud9env.yml)}

  Outputs: ${file(./resources/Outputs.yml)}
