service: ${env:SERVICE_NAME, 'RDS'}

useDotenv: true

custom:
  postgres:
    clusterIdentifier: ${self:service}-${self:provider.stage}-${param:PostgresClusterIdentifier, env:RDS_POSTGRES_CLUSTER_IDENTIFIER}
    masterUsername: ${param:PostgresMasterUsername, env:RDS_POSTGRES_MASTER_USERNAME}
    database: ${param:PostgresDatabaseName, env:RDS_POSTGRES_DATABASE_NAME}
  vpc:
    cidr: ${param:VpcCird, env:VPC_CIDR, '10.0.0.0/16'}

provider:
  name: aws
  stage: ${opt:stage, env:STAGE, 'local'}
  region: ${opt:region, env:AWS_REGION, 'us-east-1'}
  profile: ${opt:aws-profile, env:AWS_PROFILE, ''}

resources:
  - ${file(./resource/Conditions.yml)}
  - ${file(./resource/VPC.yml)}
  - ${file(./resource/VPCGateways.yml)}
  - ${file(./resource/VPCEndpoints.yml)}
  - ${file(./resource/VPCSubnets.yml)}
  - ${file(./resource/VPCRoutes.yml)}
  - ${file(./resource/RDSPostgres.yml)}
  - ${file(./resource/Cloud9env.yml)}
  - ${file(./resource/Outputs.yml)}
