apiVersion: v1
kind: Service
metadata:
  name: node-nestjs-app
  labels:
    name: node-nestjs-app
  namespace: k8s-tilt-dev-example
spec:
  selector:
    app: k8s-tilt-dev-example
    tier: node-nestjs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
