service: ${env:SERVICE_NAME, 'Middy'}

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

useDotenv: true

package:
  individually: true
  excludeDevDependencies: true

custom:
  serverless-offline:
    httpPort: 3000
    port: 3000
    noPrependStageInUrl: true

provider:
  name: aws
  stage: local
  runtime: nodejs16.x
  deploymentBucket:
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

functions:
  officialMiddlewareExample:
    handler: src/handlers/post.officialMiddlewareHandler
    events:
      - http:
           path: /
           method: POST
