Transform: AWS::SecretsManager-2020-07-23
Resources:
  RDSPostgresConnectionSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /SLS/${self:service}-${sls:stage}/rds-connection
      Description: RDS Cluster Connection Secret
      GenerateSecretString:
        SecretStringTemplate: '{ "username": "${self:custom.postgres.masterUsername}", "database": "${self:custom.postgres.database}" }'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludePunctuation: true
      Tags:
        - Key: Name
          Value: ${sls:stage}/RDS

  RDSPostgresConnectionSecretTargetAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref RDSPostgresConnectionSecret
      TargetId: !Ref RDSPostgresInstance
      TargetType: AWS::RDS::DBInstance

  RDSPostgresConnectionSecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: RDSPostgresConnectionSecretTargetAttachment
    Properties:
      SecretId: !Ref RDSPostgresConnectionSecret
      HostedRotationLambda:
        RotationType: PostgreSQLSingleUser
        RotationLambdaName: ${self:service}-${sls:stage}-rds-rotate-postgres-secret
        VpcSecurityGroupIds: !GetAtt AppSecurityGroup.GroupId
        VpcSubnetIds:
          Fn::Join:
            - ","
            - - !Ref AppSubnet1
              - !Ref AppSubnet2
      RotationRules:
        Duration: 6h
        # The secret is configured to rotate on the first Sunday
        # of every month between 4:00 AM and 6:00 AM UTC.
        ScheduleExpression: "cron(0 4 ? * SUN#1 *)"

Outputs:
  RDSPostgresConnectionSecretName:
    Description: The name of the secret that contains the connection information of the RDS Postgres instance
    Value: !Ref RDSPostgresConnectionSecret
