apiVersion: v1
kind: Service
metadata:
  name: python-fastapi-app
  labels:
    name: python-fastapi-app
  namespace: k8s-tilt-dev-example
spec:
  selector:
    app: k8s-tilt-dev-example
    tier: python-fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
