service: ${env:SERVICE_NAME}

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

useDotenv: true

package:
  individually: true
  excludeDevDependencies: true

custom:
  serverless-offline:
    httpPort: 3000
    port: 3000
    noPrependStageInUrl: true

provider:
  name: aws
  stage: local
  runtime: nodejs16.x
  deploymentBucket:
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

functions:
  sendTwilioSMS:
    handler: src/handlers/sendTwilioSMS.handler
    environment:
      TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${env:TWILIO_PHONE_NUMBER}
    events:
      - http:
          path: /send-twilio-sms
          method: POST
