---
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${env:S3_BUCKET_NAME}

Outputs:
  S3BucketNameOutputKey:
    Value: !Ref S3Bucket
    Description: S3 bucket for the example
    Export:
      Name: ${self:service}-${sls:stage}-s3-bucket
