service: ${env:SERVICE_NAME, 'serverless-fastapi-example'}

frameworkVersion: "3"

plugins:
  - serverless-python-requirements
  - serverless-offline

useDotenv: true

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - "**"
  include:
    - "!./**"
    - "**/*.py"

custom:
  pythonRequirements:
    usePipenv: true
    layer: true
    noDeploy:
      - pytest
  serverless-offline:
    httpPort: 3000
    port: 3000
    noPrependStageInUrl: true

provider:
  name: aws
  stage: local
  runtime: python3.9
  environment:
    STAGE: ${sls:stage}
  deploymentBucket:
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

functions:
  app:
    runtime: python3.9
    handler: src/main.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /docs
          method: ANY
          private: false
      - http:
          path: /openapi.json
          method: ANY
          private: false
