service: ${env:SERVICE_NAME}

frameworkVersion: "3"

plugins:
  - serverless-bundle
  - serverless-offline

useDotenv: true

package:
  individually: true
  excludeDevDependencies: true

custom:
  serverless-offline:
    httpPort: 3000
    port: 3000
    noPrependStageInUrl: true
    reloadHandler: true
  bundle:
    sourcemaps: true
    tsConfig: "./tsconfig.bundle.json"
    caching: false
    linting: true
    minifyOptions:
      keepNames: true
    packager: npm
    forceExclude:
      - "aws-sdk"

provider:
  name: aws
  stage: local
  region: us-west-2
  runtime: nodejs16.x
  deploymentBucket:
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

functions:
  get:
    handler: src/handlers/get.handler
    events:
      - http:
          method: GET
          path: /
  post:
    handler: src/handlers/post.handler
    events:
      - http:
          method: POST
          path: /
