bucketDeploy: ${self:service}-${self:provider.stage}-glue-bucket-deploy
createBucket: true
s3Prefix: ""
jobs:
  - name: pyspark
    scriptPath: app/jobs/pyspark.py
    type: spark
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/GlueJobRole/GlueJobRole
    glueVersion: python3-3.0
    MaxConcurrentRuns: 3
    WorkerType: Standard
    NumberOfWorkers: 1
    Timeout: 3000
    MaxRetries: 1
    Connections:
      - !Ref GlueConnection
    DefaultArguments:
      usePostgresDriver: true
      enableS3ParquetOptimizedCommitter: true
      enableGlueDatacatalog: true
      enableMetrics: true
      enableContinuousCloudwatchLog: true
      enableContinuousLogFilter: true
      continuousLogLogGroup: ${self:service}-${self:provider.stage}-logs
      enableSparkUi: true
      sparkEventLogsPath: s3://${self:service}-${self:provider.stage}-glue-bucket-deploy/pyspark/spark-events-logs/
      tempDir: s3://${self:service}-${self:provider.stage}-glue-bucket-deploy/tmp/
      extraPyFiles: s3://${self:service}-${self:provider.stage}-glue-bucket-deploy/package.zip
      customArguments:
        # Install additional python packages
        "additional-python-modules": "tldextract==3.3.0"
        # Pass additional arguments to the pyspark script
        "CUSTOM_ARGUMENT": "CUSTOM_VALUE"
    SupportFiles:
      - local_path: package.zip
        s3_bucket: ${self:service}-${self:provider.stage}-glue-bucket-deploy
        s3_prefix: ""
        execute_upload: true
  - name: pythonshell
    scriptPath: app/jobs/pythonshell.py
    type: pythonshell
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/GlueJobRole/GlueJobRole
    glueVersion: python3-3.0
    MaxConcurrentRuns: 3
    WorkerType: Standard
    Timeout: 3000
    MaxRetries: 1
    Connections:
      - !Ref GlueConnection
    DefaultArguments:
      usePostgresDriver: true
      enableS3ParquetOptimizedCommitter: true
      enableGlueDatacatalog: true
      enableMetrics: true
      enableContinuousCloudwatchLog: true
      enableContinuousLogFilter: true
      continuousLogLogGroup: ${self:service}-${self:provider.stage}-logs
      tempDir: s3://${self:service}-${self:provider.stage}-glue-bucket-deploy/tmp/
      extraPyFiles: s3://${self:service}-${self:provider.stage}-glue-bucket-deploy/package.zip
      customArguments:
        # Install additional python packages
        "additional-python-modules": "tldextract==3.3.0"
        # Pass additional arguments to the pythonshell script
        "CUSTOM_ARGUMENT": "CUSTOM_VALUE"
    SupportFiles:
      - local_path: package.zip
        s3_bucket: ${self:service}-${self:provider.stage}-glue-bucket-deploy
        s3_prefix: ""
        execute_upload: true
triggers:
  - name: trigger1
    Tags:
      trigger_tag_pyspark: pyspark
    actions:
      - name: pyspark
  - name: trigger2
    Tags:
      trigger_tag_pythonshell: pythonshell
    actions:
      - name: pythonshell
