[tool.black]
py37 = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | .serverless
    | .glue
    | node_modules
    | .ipynb_checkpoints

    # The following are specific to Black, you probably don't want those.
    | blib2to3
    | tests/data
)/
'''
