Resources:
  Cloud9env:
    Type: AWS::Cloud9::EnvironmentEC2
    Condition: CreateCloud9Environment
    DependsOn: DocumentDBCluster
    Properties:
      AutomaticStopTimeMinutes: 60
      Description: Cloud9 instance to access Cloud9
      InstanceType: t2.small
      Name: DocumentDBCloud9${self:service}${sls:stage}
      SubnetId: ${self:variables.values.PublicSubnetOne}
