Transform: AWS::SecretsManager-2020-07-23
Resources:
  DocumentDBConnectionSecret:
    Type: AWS::SecretsManager::Secret
    Condition: CreateDocumentDBCluster
    Properties:
      Name: ${sls:stage}/${self:service}
      Description: DocumentDB Cluster Connection Secret
      GenerateSecretString:
        SecretStringTemplate: '{ "username": "${self:custom.documentdb.masterUsername}", "database": "${self:custom.documentdb.database}" }'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludePunctuation: true
      Tags:
        - Key: Name
          Value: ${sls:stage}/DocumentDB

  DocumentDBConnectionSecretTargetAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Condition: CreateDocumentDBCluster
    Properties:
      SecretId: !Ref DocumentDBConnectionSecret
      TargetId: !Ref DocumentDBCluster
      TargetType: AWS::DocDB::DBCluster

  DocumentDBConnectionSecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    Condition: CreateDocumentDBCluster
    DependsOn: DocumentDBConnectionSecretTargetAttachment
    Properties:
      SecretId: !Ref DocumentDBConnectionSecret
      HostedRotationLambda:
        RotationType: MongoDBSingleUser
        RotationLambdaName: ${self:service}-${sls:stage}-docdb-rotate-connection-secret
        VpcSecurityGroupIds: ${self:variables.values.VPCDefaultSecurityGroup}
        VpcSubnetIds:
          Fn::Join:
            - ","
            - - ${self:variables.values.PrivateSubnetOne}
              - ${self:variables.values.PrivateSubnetTwo}
      RotationRules:
        Duration: 6h
        # The secret is configured to rotate on the first Sunday
        # of every month between 4:00 AM and 6:00 AM UTC.
        ScheduleExpression: "cron(0 4 ? * SUN#1 *)"
