Resources:
  DocumentDBCluster:
    Type: AWS::DocDB::DBCluster
    Condition: CreateDocumentDBCluster
    Properties:
      DBClusterIdentifier: ${self:custom.documentdb.clusterIdentifier}
      MasterUsername:
        Fn::Sub:
          - "{{resolve:secretsmanager:${SecretName}:SecretString:username}}"
          - SecretName: !Ref DocumentDBConnectionSecret
      MasterUserPassword:
        Fn::Sub:
          - "{{resolve:secretsmanager:${SecretName}:SecretString:password}}"
          - SecretName: !Ref DocumentDBConnectionSecret
      DBSubnetGroupName: !Ref DocumentDBSubnetGroup
      DBClusterParameterGroupName: !Ref DocumentDBClusterParameterGroup
      VpcSecurityGroupIds:
        - !Ref DocumentDBSecurityGroup

  DocumentDBClusterParameterGroup:
    Type: AWS::DocDB::DBClusterParameterGroup
    Condition: CreateDocumentDBCluster
    Properties:
      Description: DocumentDB cluster parameter group
      Name: !Sub ${self:custom.documentdb.clusterIdentifier}-cluster-parameter-group
      Family: docdb4.0
      Parameters:
        tls: enabled
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-DocumentDBClusterParameterGroup

  DocumentDBInstanceReaderOne:
    Type: AWS::DocDB::DBInstance
    Condition: CreateDocumentDBCluster
    DependsOn: DocumentDBCluster
    Properties:
      DBClusterIdentifier: ${self:custom.documentdb.clusterIdentifier}
      DBInstanceClass: db.r5.large
      Tags:
        - Key: Name
          Value: ${self:service}-${sls:stage}-documentdb-instance-reader1

  DocumentDBInstanceReaderTwo:
    Type: AWS::DocDB::DBInstance
    Condition: CreateDocumentDBCluster
    DependsOn: DocumentDBCluster
    Properties:
      DBClusterIdentifier: ${self:custom.documentdb.clusterIdentifier}
      DBInstanceClass: db.r5.large
      Tags:
        - Key: Name
          Value: ${self:service}-${sls:stage}-documentdb-instance-reader2

  DocumentDBInstanceWriter:
    Type: AWS::DocDB::DBInstance
    Condition: CreateDocumentDBCluster
    DependsOn: DocumentDBCluster
    Properties:
      DBClusterIdentifier: ${self:custom.documentdb.clusterIdentifier}
      DBInstanceClass: db.r5.large
      Tags:
        - Key: Name
          Value: ${self:service}-${sls:stage}-documentdb-instance-writer

  DocumentDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateDocumentDBCluster
    Properties:
      GroupDescription: Allow HTTP and HTTPS from anywhere
      VpcId: ${self:variables.values.VpcId}
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          CidrIp: ${self:custom.vpc.cidr}
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          CidrIp: ${env:GLUE_VPC_CIDR}
      Tags:
        - Key: Name
          Value: ${self:service}-${sls:stage}-documentdb-security-group

  DocumentDBSubnetGroup:
    Type: AWS::DocDB::DBSubnetGroup
    Condition: CreateDocumentDBCluster
    Properties:
      DBSubnetGroupDescription: ${self:service}-${sls:stage}-documentdb-subnet-group
      DBSubnetGroupName: ${self:service}-${sls:stage}-DocumentDB-subnet-group
      SubnetIds:
        - ${self:variables.values.PrivateSubnetOne}
        - ${self:variables.values.PrivateSubnetTwo}
      Tags:
        - Key: Name
          Value: ${self:service}-${sls:stage}-documentdb-subnet-group
